### ISSUE TITLE
Definition of Style in SymCore

### ISSUE THREAD

**Issue by cportele** [opengeospatial/styles-and-symbology#1]
The recently published [SymCore standard](https://docs.ogc.org/is/18-067r3/18-067r3.html) has a Style definition that is narrower than the definition that we use in OGC API Styles.

SymCore defines "style" as (see [section 4.3](https://docs.ogc.org/is/18-067r3/18-067r3.html#toc9), bolding is mine)

> a set of rules of symbolizing instructions to be applied by a rendering engine on **a layer of geographic features (e.g., feature, coverage…​)**.

In OGC API Styles, we define "style" as

> a sequence of rules of symbolizing instructions to be applied by a rendering engine on one or more features and/or coverages.

First of all, I think that "sequence" is correct (not "set", the order is in general relevant).

Second, and more importantly, SymCore restricts a style to a single data layer where layer is quite vaguely defined as

> an abstraction of reality specified by a geographic data model (feature, coverage…​). A layer may be represented using a set of symbols (Style). A layer contributes to a single geographic subject and may be a theme.

However, the intent seems to be clear that this excludes the use of "style" like in a Mapbox Style which can reference multiple data layers and multiple data sources. For OGC API Styles the narrow definition of SymCore is - in my opinion - not an option.

However, it raises two questions:

* Since SymCore describes itself as a conceptual model for styles in OGC, is that narrow definition an issue for OGC API Styles? Interestingly, SymCore is not an OGC Abstract Specification as one would expect from a conceptual model, but SymCore is a Implementation Standard. I guess that implies that the definition only applies to the OGC Symbology standards and OGC API Styles can use a different definition/model.
* The vague definition of layer in SymCore leaves room for interpretation, but in the OGC API context I think a layer would in general match a Collection. This would then imply that a style with a SymCore-based encoding can only be associated with a single collection. That would limit the usability of SymCore quite a bit. You need multiple, separate styles for most maps. It is also worth to note that the SymCore model has no concept of aggregations of styles, so it is unlikely that SymCore encodings will support anything else but single layer documents.

cc @jerstlouis

**Comment by jerstlouis** [comment]
@ebocher There is an OGC glossary of terms [here](https://www.ogc.org/ogc/glossary/s).

Here is what it says for _style_:

> **Style**: Styles provide the mapping from feature types and feature properties and constraints to parameterized symbols used in drawing maps

In the Testbed 15 Open Portrayal Framework, we looked at a consistent portrayal framework that spans both online and offline use cases, and the work done in _OGC API - Styles_ is informed by that framework, so it should not be specific to OGC API. In particular, we also developed a portrayal extension for GeoPackages.

That might be what Matt had shared (engineering report [here](https://docs.ogc.org/per/19-018.html)).

Definition of _Style_ there:

> **Style**: a sequence of rules of symbolizing instructions to be applied by a rendering engine on one or more features and/or coverages

Some of that work had also previously taken place in the Vector Tiles Pilot Extension focusing on styling ([engineering report](https://docs.ogc.org/per/18-101.html)).

**Comment by ebocher** [comment]
> That might be what Matt had shared (engineering report [here](https://docs.ogc.org/per/19-018.html)).

After a bit of archaeology, I attached it.

[portrayal_terms_2_june_2020.docx](https://github.com/opengeospatial/styles-and-symbology/files/6755419/portrayal_terms_2_june_2020.docx)

**Comment by jeffharrison** [comment]
From the Vector Tiles Pilot long, detailed dialog...

A style organizes the rules of symbolizing instructions to be applied by a rendering engine on one or more geographic features and/or coverages. (from group consensus Jan 18, 2019)

**Comment by ebocher** [comment]
@jeffharrison sounds good for me.

**Comment by chris-little** [comment]
@jeffharrison in the VTP definition, I would prefer to remove the adjective 'geographic'. What about portraying disease incidence - a coverage certainly, but not very geographic? Ditto weather use cases. Less is more!

**Comment by jerstlouis** [comment]
@chris-little @ebocher @jeffharrison 
I believe the definition from the Testbed 15 Open Portrayal Framework was an refinement of the earlier VTP definition, and therefore supersedes it:

> Style: a sequence of rules of symbolizing instructions to be applied by a rendering engine on one or more features and/or coverages

It does not contain geographic, and It also feels more like a definition (rather than saying what a style does).

**Comment by jeffharrison** [comment]
Sounds good!

**Comment by jerstlouis** [comment]
SWG 2021-12-07: Today we approve that definition from Open Portrayal Framework:

> Style: a sequence of rules of symbolizing instructions to be applied by a rendering engine on one or more features and/or coverages
