### ISSUE TITLE
Inconsistent naming of RelationalOperator

### ISSUE THREAD

**Issue by jansule** [opengeospatial/styles-and-symbology#42]
The naming of the enumerations of the `RelationalOperator` are inconsisten between the table and the UML class diagram in https://github.com/opengeospatial/styles-and-symbology/blob/main/core/sections/clause_7_core.adoc#operation-expressions. E.g the UML class diagram states a value `equal` whereas the table states `equalTo`.

![image](https://user-images.githubusercontent.com/12186477/234591898-fe4c5794-0070-424d-8b0b-d18203b302e3.png)

**Comment by jerstlouis** [comment]
Fixed.
